### ISSUE TITLE
Implement ZoneKind

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#1326]
thoughts for kick off...

we want a new Zone manifest:

```yaml
---
kind: Zone
spec:
  name: My Cool Zone 
  description: "Does cool stuff"
  image: http://imgur.com/mycoolimage.png 
  contract:
    file: ./CoolZone.sol
  plugin:
    file: ./CoolZone.js
```

the zone owner can apply the zone manifest which will:

* set the name (required)
* set the description (required)
* set the image url (optional)
* deploy and register a Zone implementation contract (optional)
    * there can only ever be one Zone implementation per zone
    * the Zone implementation should conform the BaseZone/IZone interface (sketched below)
* deploy and register a Zone plugin js (optional)
    * There can only eveer to one Zone plugin per zone 
    * Zone plugins are ALWAYS always active 

A Zone implementation:

* conforms to an interface to allow hooking into common game actions (ie `onMovedMobileUnit()`, `onConstructedBuilding()`, etc)
* the hooks pass along all the relevent args from the original action(s) so that decent decisions can be made
* reverts in hook should revert the original action... but IT MUST NOT BE POSSIBLE TO PREVENT A UNIT LEAVING THE ZONE! 
* ... think: are there any other things that could brick the player?
* there should be a generic `use` type function exposed (just like BuildingKind) and an equivilent `ZONE_USE(actor, payload)` action that can be dispatched by any actor in the zone (I think this means only mobile units? discuss)
* the aim of the `use` is allow an entrypoint for calling the zone contract that is NOT a hook so that for example a plugin could ask the contract to reset stuff

Zone implementation contracts can call DEV_ cheats...

* All the DEV_ actions for a zone should be callable by both the owner AND the zone implementation
