### ISSUE TITLE
ds-cli: support constructor args for building contracts

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#505]
currently the building manifest and ds-cli does not allow you to specify constructor args for your contract ... so only param-less contract constructors are supported

we should allow defining them in the manifest:

```
kind: building
name: spoon factory
contract:
  file: ./Building.sol
  constructor:
  - type: bytes4
    value: "0x709735"
  - type: string
    value: "hello"
  - type: address
    value: "0xmeeeeeee"
```
